import "../src/futhark"

importc:
  path "."
  "talias.h"

doAssert CYW43_SUP_DISCONNECTED == 0
doAssert CYW43_SUP_CONNECTING == 1
doAssert CYW43_SUP_IDREQUIRED == 2
doAssert CYW43_SUP_AUTHENTICATING == 3
doAssert CYW43_SUP_AUTHENTICATED == 4
doAssert CYW43_SUP_KEYXCHANGE == 5
doAssert CYW43_SUP_KEYED == 6
doAssert CYW43_SUP_TIMEOUT == 7
doAssert CYW43_SUP_LAST_BASIC_STATE == 8
doAssert CYW43_SUP_KEYXCHANGE_WAIT_M1 == CYW43_SUP_AUTHENTICATED
doAssert CYW43_SUP_KEYXCHANGE_PREP_M2 == CYW43_SUP_KEYXCHANGE
doAssert CYW43_SUP_KEYXCHANGE_WAIT_M3 == CYW43_SUP_LAST_BASIC_STATE
doAssert CYW43_SUP_KEYXCHANGE_PREP_M4 == 9
doAssert CYW43_SUP_KEYXCHANGE_WAIT_G1 == 10
doAssert CYW43_SUP_KEYXCHANGE_PREP_G2 == 11
